/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Lab-NTM-01
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblUser = new javax.swing.JLabel();
        JtxtUsuario = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLblSenha = new javax.swing.JLabel();
        jLblCarro = new javax.swing.JLabel();
        jBtnAcessar = new javax.swing.JButton();
        JlblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eFeira - Autenticação");
        getContentPane().setLayout(null);

        jLblUser.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        jLblUser.setForeground(new java.awt.Color(255, 153, 0));
        jLblUser.setText("Usuário");
        getContentPane().add(jLblUser);
        jLblUser.setBounds(180, 70, 70, 13);

        JtxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(JtxtUsuario);
        JtxtUsuario.setBounds(160, 90, 110, 20);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(160, 130, 110, 20);

        jLblSenha.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        jLblSenha.setForeground(new java.awt.Color(255, 153, 0));
        jLblSenha.setText("Senha");
        getContentPane().add(jLblSenha);
        jLblSenha.setBounds(190, 110, 50, 13);

        jLblCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carro teste.png"))); // NOI18N
        getContentPane().add(jLblCarro);
        jLblCarro.setBounds(60, 0, 260, 260);

        jBtnAcessar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnAcessar.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        jBtnAcessar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/login teste.png"))); // NOI18N
        jBtnAcessar.setOpaque(false);
        getContentPane().add(jBtnAcessar);
        jBtnAcessar.setBounds(160, 260, 90, 20);

        JlblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(JlblFundo);
        JlblFundo.setBounds(0, 0, 390, 300);

        setSize(new java.awt.Dimension(402, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JtxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlblFundo;
    private javax.swing.JTextField JtxtUsuario;
    private javax.swing.JButton jBtnAcessar;
    private javax.swing.JLabel jLblCarro;
    private javax.swing.JLabel jLblSenha;
    private javax.swing.JLabel jLblUser;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
