/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansCliente;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import modeloDao.DaoCliente;

/**
 *
 * @author Lab-NTM-01
 */
public class TelaCliente extends javax.swing.JFrame {

    BeansCliente mod = new BeansCliente();
    ConexaoBD conex = new ConexaoBD();
    DaoCliente control = new DaoCliente();
    private int flag;
    /**
     * Creates new form TelaEstoque
     */
    public TelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeral = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelRegistro = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTxtNome = new javax.swing.JTextField();
        jTxtId = new javax.swing.JTextField();
        jTxtCPF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLblImg = new javax.swing.JLabel();
        jBtnNovo = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jPanelTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setSize(new java.awt.Dimension(300, 300));

        jPanelGeral.setBackground(new java.awt.Color(204, 204, 204));
        jPanelGeral.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon 64.png"))); // NOI18N
        jPanelGeral.add(jLabel4);
        jLabel4.setBounds(354, 0, 70, 60);

        jPanelRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastrar Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelRegistro.setOpaque(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jTxtNome.setFont(new java.awt.Font("Gill Sans MT", 0, 10)); // NOI18N
        jTxtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(jTxtNome);
        jTxtNome.setBounds(200, 180, 140, 19);

        jTxtId.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTxtId.setForeground(new java.awt.Color(255, 255, 255));
        jTxtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtId.setText("ID");
        jTxtId.setEnabled(false);
        jTxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdActionPerformed(evt);
            }
        });
        jPanel3.add(jTxtId);
        jTxtId.setBounds(340, 50, 40, 20);

        jTxtCPF.setFont(new java.awt.Font("Gill Sans MT", 0, 10)); // NOI18N
        jTxtCPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtCPF.setEnabled(false);
        jTxtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCPFActionPerformed(evt);
            }
        });
        jPanel3.add(jTxtCPF);
        jTxtCPF.setBounds(200, 200, 140, 19);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(150, 180, 50, 20);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(150, 200, 60, 20);

        jLblImg.setBackground(new java.awt.Color(184, 108, 39));
        jLblImg.setForeground(new java.awt.Color(184, 108, 39));
        jLblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/teste 2 usuario.png"))); // NOI18N
        jPanel3.add(jLblImg);
        jLblImg.setBounds(120, -13, 260, 280);

        jBtnNovo.setBackground(new java.awt.Color(0, 0, 255));
        jBtnNovo.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        jBtnNovo.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        jBtnNovo.setBorder(null);
        jBtnNovo.setBorderPainted(false);
        jBtnNovo.setContentAreaFilled(false);
        jBtnNovo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo selecionado.png"))); // NOI18N
        jBtnNovo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo mouse.png"))); // NOI18N
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnNovo);
        jBtnNovo.setBounds(40, 10, 77, 37);

        jBtnEditar.setBackground(new java.awt.Color(0, 0, 255));
        jBtnEditar.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        jBtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jBtnEditar.setBorder(null);
        jBtnEditar.setBorderPainted(false);
        jBtnEditar.setContentAreaFilled(false);
        jBtnEditar.setEnabled(false);
        jBtnEditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar selecionado.png"))); // NOI18N
        jBtnEditar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar mouse.png"))); // NOI18N
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnEditar);
        jBtnEditar.setBounds(40, 50, 77, 37);

        jBtnCancelar.setBackground(new java.awt.Color(0, 0, 255));
        jBtnCancelar.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        jBtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cancelar.png"))); // NOI18N
        jBtnCancelar.setBorder(null);
        jBtnCancelar.setBorderPainted(false);
        jBtnCancelar.setContentAreaFilled(false);
        jBtnCancelar.setEnabled(false);
        jBtnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar selecionado.png"))); // NOI18N
        jBtnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar mouse.png"))); // NOI18N
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnCancelar);
        jBtnCancelar.setBounds(40, 90, 77, 35);

        jBtnSalvar.setBackground(new java.awt.Color(0, 0, 255));
        jBtnSalvar.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        jBtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        jBtnSalvar.setBorder(null);
        jBtnSalvar.setBorderPainted(false);
        jBtnSalvar.setContentAreaFilled(false);
        jBtnSalvar.setEnabled(false);
        jBtnSalvar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar selecionado.png"))); // NOI18N
        jBtnSalvar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar mouse.png"))); // NOI18N
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnSalvar);
        jBtnSalvar.setBounds(40, 130, 77, 35);

        jBtnExcluir.setBackground(new java.awt.Color(0, 0, 255));
        jBtnExcluir.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        jBtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        jBtnExcluir.setBorder(null);
        jBtnExcluir.setBorderPainted(false);
        jBtnExcluir.setContentAreaFilled(false);
        jBtnExcluir.setEnabled(false);
        jBtnExcluir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir selecionado.png"))); // NOI18N
        jBtnExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir mouse.png"))); // NOI18N
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnExcluir);
        jBtnExcluir.setBounds(40, 170, 79, 35);

        javax.swing.GroupLayout jPanelRegistroLayout = new javax.swing.GroupLayout(jPanelRegistro);
        jPanelRegistro.setLayout(jPanelRegistroLayout);
        jPanelRegistroLayout.setHorizontalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRegistroLayout.setVerticalGroup(
            jPanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelGeral.add(jPanelRegistro);
        jPanelRegistro.setBounds(10, 10, 400, 250);

        jPanelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Clientes Cadastrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelTabela.setOpaque(false);

        jTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTClientes);

        javax.swing.GroupLayout jPanelTabelaLayout = new javax.swing.GroupLayout(jPanelTabela);
        jPanelTabela.setLayout(jPanelTabelaLayout);
        jPanelTabelaLayout.setHorizontalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanelTabelaLayout.setVerticalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        jPanelGeral.add(jPanelTabela);
        jPanelTabela.setBounds(10, 290, 400, 150);

        jBtnPesquisar.setBackground(new java.awt.Color(0, 0, 255));
        jBtnPesquisar.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        jBtnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setBorder(null);
        jBtnPesquisar.setBorderPainted(false);
        jBtnPesquisar.setContentAreaFilled(false);
        jBtnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnPesquisar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar selecionado.png"))); // NOI18N
        jBtnPesquisar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar mouse.png"))); // NOI18N
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        jPanelGeral.add(jBtnPesquisar);
        jBtnPesquisar.setBounds(320, 260, 79, 37);

        jBtnSair.setBackground(new java.awt.Color(0, 0, 255));
        jBtnSair.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        jBtnSair.setBorderPainted(false);
        jBtnSair.setContentAreaFilled(false);
        jBtnSair.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair selecionado.png"))); // NOI18N
        jBtnSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair mouse.png"))); // NOI18N
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });
        jPanelGeral.add(jBtnSair);
        jBtnSair.setBounds(160, 440, 80, 43);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo principal2.jpg"))); // NOI18N
        jPanelGeral.add(jLabel2);
        jLabel2.setBounds(0, -20, 420, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(436, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCPFActionPerformed

    private void jTxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        if(jTxtNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o 'Nome' para continuar");
            jTxtNome.requestFocus();
        }else if(jTxtNome.getText().isEmpty() && jTxtCPF.getSize().equals(11)){
            JOptionPane.showMessageDialog(null, "Preencha o 'CPF' para continuar");
            jTxtCPF.requestFocus();
        }else if(flag==1){
            mod.setNome(jTxtNome.getText());
            mod.setCpf(jTxtCPF.getText());
            control.Salvar(mod);
            jTxtCPF.setText("");
            jTxtNome.setText("");
            jBtnSalvar.setEnabled(false);
            jBtnCancelar.setEnabled(false);
            jBtnEditar.setEnabled(false);
            jTxtCPF.setEnabled(false);
            preencherTabela("select *from clientes where id_cliente > 1 order by nome_cliente");
        }else{
            mod.setNome(jTxtNome.getText());
            mod.setCpf(jTxtCPF.getText());
            control.Editar(mod);
            jTxtNome.setText("");
            jTxtCPF.setText("");
            jBtnSalvar.setEnabled(false);
            jBtnCancelar.setEnabled(false);
            jBtnEditar.setEnabled(false);
            jTxtCPF.setEnabled(false);
            preencherTabela("select *from clientes where id_cliente > 1 order by nome_cliente");
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        flag=2;
        jBtnSalvar.setEnabled(true);
        jBtnCancelar.setEnabled(true);
        jBtnEditar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jBtnCancelar.setEnabled(true);
        jTxtCPF.setEditable(true);
        mod.setAuxiliar(jTxtCPF.getText());
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        flag=1;
        jBtnSalvar.setEnabled(true);
        jBtnCancelar.setEnabled(true);
        jBtnPesquisar.setEnabled(false);
        jTxtCPF.setEnabled(true);
        jTxtCPF.setText("");
        jTxtNome.setText("");
    }//GEN-LAST:event_jBtnNovoActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nome","CPF"};
        conex.conexao();
        conex.executaSql("select *from clientes where nome_cliente like'%"+jTxtNome.getText()+"%'");
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getString("nome_cliente"),conex.rs.getString("cpf_cliente")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array: \n"+ex.getMessage());
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTClientes.setModel(modelo);
        jTClientes.getColumnModel().getColumn(0).setPreferredWidth(276);
        jTClientes.getColumnModel().getColumn(0).setResizable(false);
        jTClientes.getColumnModel().getColumn(1).setPreferredWidth(105);
        jTClientes.getColumnModel().getColumn(1).setResizable(false);
        jTClientes.getTableHeader().setReorderingAllowed(false);
        jTClientes.setAutoResizeMode(jTClientes.AUTO_RESIZE_OFF);
        jTClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
        
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        jBtnSalvar.setEnabled(false);
        jBtnCancelar.setEnabled(false);
        jBtnEditar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jTxtCPF.setEnabled(false);
        jTxtCPF.setText("");
        jTxtNome.setText("");
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientesMouseClicked
        String nome_cliente = ""+jTClientes.getValueAt(jTClientes.getSelectedRow(),0);
        conex.conexao();
        conex.executaSql("select *from clientes where nome_cliente='"+nome_cliente+"'");
        try {
            conex.rs.first();
            jTxtId.setText(String.valueOf(conex.rs.getInt("id_cliente")));
            jTxtNome.setText(conex.rs.getString("nome_cliente"));
            jTxtCPF.setText(conex.rs.getString("cpf_cliente"));
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar dados!\n"+ex.getMessage());
        }
        conex.desconecta();
        jBtnEditar.setEnabled(true);
        jBtnExcluir.setEnabled(true);
        jBtnCancelar.setEnabled(true);
    }//GEN-LAST:event_jTClientesMouseClicked

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        int resposta;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if(resposta == JOptionPane.YES_OPTION){
            mod.setCpf((jTxtCPF.getText()));
            control.Excluir(mod);
        }   
        preencherTabela("select *from clientes where id_cliente > 1 order by nome_cliente");
        jBtnExcluir.setEnabled(false);
        jBtnEditar.setEnabled(false);
        jTxtNome.setText("");
        jTxtId.setText("");
        jTxtCPF.setText("");
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        dispose();
        TelaPrincipal obj = new TelaPrincipal();
        obj.setVisible(true);
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nome","CPF"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getString("nome_cliente"),conex.rs.getString("cpf_cliente")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o Array: \n"+ex.getMessage());
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTClientes.setModel(modelo);
        jTClientes.getColumnModel().getColumn(0).setPreferredWidth(276);
        jTClientes.getColumnModel().getColumn(0).setResizable(false);
        jTClientes.getColumnModel().getColumn(1).setPreferredWidth(105);
        jTClientes.getColumnModel().getColumn(1).setResizable(false);
        jTClientes.getTableHeader().setReorderingAllowed(false);
        jTClientes.setAutoResizeMode(jTClientes.AUTO_RESIZE_OFF);
        jTClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblImg;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelGeral;
    private javax.swing.JPanel jPanelRegistro;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTClientes;
    private javax.swing.JTextField jTxtCPF;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables
}
