/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Lab-NTM-01
 */
public class TelaEstoque extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstoque
     */
    public TelaEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTxtVenda = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jTxtCompra = new javax.swing.JTextField();
        jTxtId = new javax.swing.JTextField();
        jTxtCod = new javax.swing.JTextField();
        jTxtQuant = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBtnNovo = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(300, 300));

        jPanel2.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 1, 12), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel1.setOpaque(false);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jTxtVenda.setForeground(new java.awt.Color(255, 153, 0));
        jTxtVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtVendaActionPerformed(evt);
            }
        });
        jPanel3.add(jTxtVenda);
        jTxtVenda.setBounds(260, 120, 60, 20);

        jTxtNome.setForeground(new java.awt.Color(255, 153, 0));
        jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeActionPerformed(evt);
            }
        });
        jPanel3.add(jTxtNome);
        jTxtNome.setBounds(190, 60, 130, 20);

        jTxtCompra.setForeground(new java.awt.Color(255, 153, 0));
        jTxtCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(jTxtCompra);
        jTxtCompra.setBounds(190, 120, 60, 20);

        jTxtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtId.setText("ID");
        jTxtId.setEnabled(false);
        jTxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdActionPerformed(evt);
            }
        });
        jPanel3.add(jTxtId);
        jTxtId.setBounds(350, 0, 31, 19);

        jTxtCod.setForeground(new java.awt.Color(255, 153, 0));
        jTxtCod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(jTxtCod);
        jTxtCod.setBounds(260, 90, 60, 20);

        jTxtQuant.setForeground(new java.awt.Color(255, 153, 0));
        jTxtQuant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantActionPerformed(evt);
            }
        });
        jPanel3.add(jTxtQuant);
        jTxtQuant.setBounds(190, 90, 60, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carro teste.png"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(120, -23, 260, 280);

        jBtnNovo.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jBtnNovo.setForeground(new java.awt.Color(255, 153, 0));
        jBtnNovo.setText("Novo");
        jBtnNovo.setOpaque(false);
        jPanel3.add(jBtnNovo);
        jBtnNovo.setBounds(20, 40, 100, 23);

        jBtnEditar.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jBtnEditar.setForeground(new java.awt.Color(255, 153, 0));
        jBtnEditar.setText("Editar");
        jBtnEditar.setOpaque(false);
        jPanel3.add(jBtnEditar);
        jBtnEditar.setBounds(20, 70, 100, 23);

        jBtnCancelar.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jBtnCancelar.setForeground(new java.awt.Color(255, 153, 0));
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setOpaque(false);
        jPanel3.add(jBtnCancelar);
        jBtnCancelar.setBounds(20, 100, 100, 23);

        jBtnSalvar.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jBtnSalvar.setForeground(new java.awt.Color(255, 153, 0));
        jBtnSalvar.setText("Salvar");
        jBtnSalvar.setOpaque(false);
        jPanel3.add(jBtnSalvar);
        jBtnSalvar.setBounds(20, 130, 100, 23);

        jBtnExcluir.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 11)); // NOI18N
        jBtnExcluir.setForeground(new java.awt.Color(255, 153, 0));
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setOpaque(false);
        jPanel3.add(jBtnExcluir);
        jBtnExcluir.setBounds(20, 160, 100, 23);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 10, 400, 260);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 420, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(436, 481));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantActionPerformed

    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeActionPerformed

    private void jTxtVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtVendaActionPerformed

    private void jTxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTxtCod;
    private javax.swing.JTextField jTxtCompra;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtQuant;
    private javax.swing.JTextField jTxtVenda;
    // End of variables declaration//GEN-END:variables
}
