/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Lab-NTM-01
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindos = new javax.swing.JInternalFrame();
        jLblTitulo = new javax.swing.JLabel();
        jPanelBemVindo = new javax.swing.JPanel();
        jPanelVendas = new javax.swing.JPanel();
        jBtnComprar = new javax.swing.JButton();
        JPanelCadastros = new javax.swing.JPanel();
        jBtnProduto = new javax.swing.JButton();
        jBtnCliente = new javax.swing.JButton();
        jBtnRelatorios = new javax.swing.JButton();
        jLblPainelFundo = new javax.swing.JLabel();
        jLblFundo = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuOrganizarEstoque = new javax.swing.JMenu();
        jMenuItemEstoque = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRendimento = new javax.swing.JMenuItem();
        jMenuProdutos = new javax.swing.JMenu();
        jMenuItemVerProdutos = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eFeira - Cayque Silva");
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameBemVindos.setTitle("Bem vindo ao EFeira");
        jInternalFrameBemVindos.setVisible(true);

        jLblTitulo.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLblTitulo.setForeground(new java.awt.Color(255, 153, 0));
        jLblTitulo.setText("Sistema eFeira");

        jPanelBemVindo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanelBemVindo.setLayout(null);

        jPanelVendas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ver Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 1, 11), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanelVendas.setForeground(new java.awt.Color(255, 255, 255));
        jPanelVendas.setOpaque(false);

        jBtnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/comprar teste.png"))); // NOI18N
        jBtnComprar.setToolTipText("Ver Produtos à Venda");

        javax.swing.GroupLayout jPanelVendasLayout = new javax.swing.GroupLayout(jPanelVendas);
        jPanelVendas.setLayout(jPanelVendasLayout);
        jPanelVendasLayout.setHorizontalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVendasLayout.setVerticalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasLayout.createSequentialGroup()
                .addComponent(jBtnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanelBemVindo.add(jPanelVendas);
        jPanelVendas.setBounds(390, 10, 130, 130);

        JPanelCadastros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 1, 11), new java.awt.Color(255, 153, 0))); // NOI18N
        JPanelCadastros.setForeground(new java.awt.Color(255, 255, 255));
        JPanelCadastros.setOpaque(false);

        jBtnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estoque teste.png"))); // NOI18N
        jBtnProduto.setToolTipText("Organizar Estoque");
        jBtnProduto.setBorder(null);
        jBtnProduto.setBorderPainted(false);
        jBtnProduto.setName(""); // NOI18N
        jBtnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProdutoActionPerformed(evt);
            }
        });

        jBtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/clientes teste.png"))); // NOI18N
        jBtnCliente.setToolTipText("Gerenciar Clientes");
        jBtnCliente.setBorder(null);
        jBtnCliente.setBorderPainted(false);

        jBtnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorios teste.png"))); // NOI18N
        jBtnRelatorios.setToolTipText("Ver Rendimento Atual");

        javax.swing.GroupLayout JPanelCadastrosLayout = new javax.swing.GroupLayout(JPanelCadastros);
        JPanelCadastros.setLayout(JPanelCadastrosLayout);
        JPanelCadastrosLayout.setHorizontalGroup(
            JPanelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCadastrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        JPanelCadastrosLayout.setVerticalGroup(
            JPanelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCadastrosLayout.createSequentialGroup()
                .addGroup(JPanelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBemVindo.add(JPanelCadastros);
        JPanelCadastros.setBounds(10, 10, 370, 130);

        jLblPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.jpg"))); // NOI18N
        jLblPainelFundo.setText("jLabel1");
        jPanelBemVindo.add(jLblPainelFundo);
        jLblPainelFundo.setBounds(-10, 0, 550, 190);

        javax.swing.GroupLayout jInternalFrameBemVindosLayout = new javax.swing.GroupLayout(jInternalFrameBemVindos.getContentPane());
        jInternalFrameBemVindos.getContentPane().setLayout(jInternalFrameBemVindosLayout);
        jInternalFrameBemVindosLayout.setHorizontalGroup(
            jInternalFrameBemVindosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameBemVindosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitulo)
                .addContainerGap(365, Short.MAX_VALUE))
            .addComponent(jPanelBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrameBemVindosLayout.setVerticalGroup(
            jInternalFrameBemVindosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameBemVindosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jInternalFrameBemVindos);
        jInternalFrameBemVindos.setBounds(0, 40, 550, 280);

        jLblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLblFundo);
        jLblFundo.setBounds(0, 0, 560, 390);

        jMenuOrganizarEstoque.setText("Organizar Estoque");

        jMenuItemEstoque.setText("Organizar Estoque");
        jMenuOrganizarEstoque.add(jMenuItemEstoque);
        jMenuOrganizarEstoque.add(jSeparator1);

        jMenuItemClientes.setText("Cadastrar Clientes");
        jMenuOrganizarEstoque.add(jMenuItemClientes);
        jMenuOrganizarEstoque.add(jSeparator2);

        jMenuItemRendimento.setText("Ver Rendimento Atual");
        jMenuOrganizarEstoque.add(jMenuItemRendimento);

        jMenuBar.add(jMenuOrganizarEstoque);

        jMenuProdutos.setText("Ver Produtos à Venda");

        jMenuItemVerProdutos.setText("Ver Produtos");
        jMenuProdutos.add(jMenuItemVerProdutos);

        jMenuBar.add(jMenuProdutos);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemBemVindo.setText("Tela Bem-Vindo");
        jMenuFerramentas.add(jMenuItemBemVindo);

        jMenuBar.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuSair.add(jMenuItemSair);

        jMenuBar.add(jMenuSair);

        setJMenuBar(jMenuBar);

        setSize(new java.awt.Dimension(554, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelCadastros;
    private javax.swing.JButton jBtnCliente;
    private javax.swing.JButton jBtnComprar;
    private javax.swing.JButton jBtnProduto;
    private javax.swing.JButton jBtnRelatorios;
    private javax.swing.JInternalFrame jInternalFrameBemVindos;
    private javax.swing.JLabel jLblFundo;
    private javax.swing.JLabel jLblPainelFundo;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemBemVindo;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemEstoque;
    private javax.swing.JMenuItem jMenuItemRendimento;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVerProdutos;
    private javax.swing.JMenu jMenuOrganizarEstoque;
    private javax.swing.JMenu jMenuProdutos;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelBemVindo;
    private javax.swing.JPanel jPanelVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
