/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import modeloConection.ConexaoBD;
import modeloDao.DaoCliente;

/**
 *
 * @author Lab-NTM-01
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD(); //instanciando o objeto da classe conexaoBD
    DaoCliente controle = new DaoCliente();
    public int flag;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conecta.conexao();
        removerTittle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindos = new javax.swing.JInternalFrame();
        jLblTitulo = new javax.swing.JLabel();
        jPanelBemVindo = new javax.swing.JPanel();
        jPanelVendas = new javax.swing.JPanel();
        jBtnComprar = new javax.swing.JButton();
        JPanelCadastros = new javax.swing.JPanel();
        jBtnProduto = new javax.swing.JButton();
        jBtnCliente = new javax.swing.JButton();
        jBtnRelatorios = new javax.swing.JButton();
        jLblPainelFundo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuOrganizarEstoque = new javax.swing.JMenu();
        jMenuItemEstoque = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemRendimento = new javax.swing.JMenuItem();
        jMenuProdutos = new javax.swing.JMenu();
        jMenuItemVerProdutos = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eFeira - Cayque Silva");
        setBackground(new java.awt.Color(51, 255, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameBemVindos.setBackground(new java.awt.Color(153, 153, 153));
        jInternalFrameBemVindos.setForeground(new java.awt.Color(255, 255, 255));
        jInternalFrameBemVindos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jInternalFrameBemVindos.setFrameIcon(null);
        jInternalFrameBemVindos.setVisible(true);

        jLblTitulo.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLblTitulo.setText("Sistema eFeira");

        jPanelBemVindo.setBackground(new java.awt.Color(21, 103, 164));
        jPanelBemVindo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanelBemVindo.setForeground(new java.awt.Color(51, 153, 255));
        jPanelBemVindo.setLayout(null);

        jPanelVendas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ver Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelVendas.setForeground(new java.awt.Color(255, 255, 255));
        jPanelVendas.setOpaque(false);

        jBtnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/comprarprodutos.png"))); // NOI18N
        jBtnComprar.setToolTipText("Ver Produtos à Venda");
        jBtnComprar.setBorderPainted(false);
        jBtnComprar.setContentAreaFilled(false);
        jBtnComprar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/comprarprodutos selecionado.png"))); // NOI18N
        jBtnComprar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/comprarprodutos mouse.png"))); // NOI18N
        jBtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVendasLayout = new javax.swing.GroupLayout(jPanelVendas);
        jPanelVendas.setLayout(jPanelVendasLayout);
        jPanelVendasLayout.setHorizontalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelVendasLayout.setVerticalGroup(
            jPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelBemVindo.add(jPanelVendas);
        jPanelVendas.setBounds(40, 160, 130, 140);

        JPanelCadastros.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Administrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        JPanelCadastros.setForeground(new java.awt.Color(255, 255, 255));
        JPanelCadastros.setOpaque(false);

        jBtnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estoque mouse.png"))); // NOI18N
        jBtnProduto.setToolTipText("Organizar Estoque");
        jBtnProduto.setBorder(null);
        jBtnProduto.setBorderPainted(false);
        jBtnProduto.setContentAreaFilled(false);
        jBtnProduto.setName(""); // NOI18N
        jBtnProduto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estoque.png"))); // NOI18N
        jBtnProduto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estoque selecionado.png"))); // NOI18N
        jBtnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProdutoActionPerformed(evt);
            }
        });

        jBtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/clientes.png"))); // NOI18N
        jBtnCliente.setToolTipText("Gerenciar Clientes");
        jBtnCliente.setBorder(null);
        jBtnCliente.setBorderPainted(false);
        jBtnCliente.setContentAreaFilled(false);
        jBtnCliente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/clientes selecionado.png"))); // NOI18N
        jBtnCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/clientes mouse.png"))); // NOI18N
        jBtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClienteActionPerformed(evt);
            }
        });

        jBtnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorios.png"))); // NOI18N
        jBtnRelatorios.setToolTipText("Ver Rendimento Atual");
        jBtnRelatorios.setBorderPainted(false);
        jBtnRelatorios.setContentAreaFilled(false);
        jBtnRelatorios.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorios selecionado.png"))); // NOI18N
        jBtnRelatorios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorios mouse.png"))); // NOI18N
        jBtnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRelatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelCadastrosLayout = new javax.swing.GroupLayout(JPanelCadastros);
        JPanelCadastros.setLayout(JPanelCadastrosLayout);
        JPanelCadastrosLayout.setHorizontalGroup(
            JPanelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCadastrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnProduto)
                .addGap(18, 18, 18)
                .addComponent(jBtnCliente)
                .addGap(18, 18, 18)
                .addComponent(jBtnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelCadastrosLayout.setVerticalGroup(
            JPanelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCadastrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCliente)
                    .addComponent(jBtnProduto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBemVindo.add(JPanelCadastros);
        JPanelCadastros.setBounds(40, 10, 370, 140);

        jLblPainelFundo.setBackground(new java.awt.Color(204, 204, 204));
        jLblPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/efeira principal.png"))); // NOI18N
        jPanelBemVindo.add(jLblPainelFundo);
        jLblPainelFundo.setBounds(500, 10, 270, 270);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cancelar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar selecionado.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar mouse.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameBemVindosLayout = new javax.swing.GroupLayout(jInternalFrameBemVindos.getContentPane());
        jInternalFrameBemVindos.getContentPane().setLayout(jInternalFrameBemVindosLayout);
        jInternalFrameBemVindosLayout.setHorizontalGroup(
            jInternalFrameBemVindosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jInternalFrameBemVindosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(531, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameBemVindosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );
        jInternalFrameBemVindosLayout.setVerticalGroup(
            jInternalFrameBemVindosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameBemVindosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        getContentPane().add(jInternalFrameBemVindos);
        jInternalFrameBemVindos.setBounds(0, 20, 800, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo principal2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -40, 800, 540);

        jMenuOrganizarEstoque.setText("Organizar Estoque");

        jMenuItemEstoque.setText("Organizar Estoque");
        jMenuItemEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstoqueActionPerformed(evt);
            }
        });
        jMenuOrganizarEstoque.add(jMenuItemEstoque);
        jMenuOrganizarEstoque.add(jSeparator1);

        jMenuItemClientes.setText("Cadastrar Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuOrganizarEstoque.add(jMenuItemClientes);
        jMenuOrganizarEstoque.add(jSeparator2);

        jMenuItemRendimento.setText("Ver Rendimento Atual");
        jMenuItemRendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRendimentoActionPerformed(evt);
            }
        });
        jMenuOrganizarEstoque.add(jMenuItemRendimento);

        jMenuBar.add(jMenuOrganizarEstoque);

        jMenuProdutos.setText("Ver Produtos à Venda");

        jMenuItemVerProdutos.setText("Ver Produtos");
        jMenuItemVerProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerProdutosActionPerformed(evt);
            }
        });
        jMenuProdutos.add(jMenuItemVerProdutos);

        jMenuBar.add(jMenuProdutos);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemBemVindo.setText("Tela Bem-Vindo");
        jMenuItemBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemBemVindo);

        jMenuBar.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar.add(jMenuSair);

        setJMenuBar(jMenuBar);

        setSize(new java.awt.Dimension(807, 512));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProdutoActionPerformed
        flag=0;
        dispose();
        TelaLogin obj = new TelaLogin(flag);
        obj.setVisible(true);
    }//GEN-LAST:event_jBtnProdutoActionPerformed

    private void jBtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClienteActionPerformed
        flag=1;
        dispose();
        TelaLogin obj = new TelaLogin(flag);
        obj.setVisible(true);
    }//GEN-LAST:event_jBtnClienteActionPerformed

    private void jBtnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRelatoriosActionPerformed
        flag=2;
        dispose();
        TelaLogin obj = new TelaLogin(flag);
        obj.setVisible(true);
    }//GEN-LAST:event_jBtnRelatoriosActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        conecta.desconecta();
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jBtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnComprarActionPerformed
        if(controle.ContarClientes()<2){
            JOptionPane.showMessageDialog(null, "Você precisa cadastrar algum cliente primeiro!!!");
        }else{
            dispose();
            TelaComprarProdutos obj = new TelaComprarProdutos();
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jBtnComprarActionPerformed

    private void jMenuItemEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstoqueActionPerformed
        flag=0;
        dispose();
        TelaLogin obj = new TelaLogin(flag);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItemEstoqueActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        flag=1;
        dispose();
        TelaLogin obj = new TelaLogin(flag);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemRendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRendimentoActionPerformed
        flag=2;
        dispose();
        TelaLogin obj = new TelaLogin(flag);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItemRendimentoActionPerformed

    private void jMenuItemVerProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerProdutosActionPerformed
        if(controle.ContarClientes()<2){
            JOptionPane.showMessageDialog(null, "Você precisa cadastrar algum cliente primeiro!!!");
        }else{
            dispose();
            TelaComprarProdutos obj = new TelaComprarProdutos();
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemVerProdutosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jInternalFrameBemVindos.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBemVindoActionPerformed
        jInternalFrameBemVindos.setVisible(true);
    }//GEN-LAST:event_jMenuItemBemVindoActionPerformed

    public void removerTittle(){
        jInternalFrameBemVindos.setFrameIcon(null);
        BasicInternalFrameUI ui = (BasicInternalFrameUI) jInternalFrameBemVindos.getUI();
        Container north = (Container) ui.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelCadastros;
    private javax.swing.JButton jBtnCliente;
    private javax.swing.JButton jBtnComprar;
    private javax.swing.JButton jBtnProduto;
    private javax.swing.JButton jBtnRelatorios;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrameBemVindos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblPainelFundo;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemBemVindo;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemEstoque;
    private javax.swing.JMenuItem jMenuItemRendimento;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVerProdutos;
    private javax.swing.JMenu jMenuOrganizarEstoque;
    private javax.swing.JMenu jMenuProdutos;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelBemVindo;
    private javax.swing.JPanel jPanelVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
